### ISSUE TITLE
[FEATURE]: Implement Author Profile for Betarena

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/boilerplate#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 📝 Description

Develop the author profile section for Betarena, which displays user profiles as authors, including their publications and other relevant information. The profile will offer functionalities for users to subscribe or follow the author.

#### Features:

1. **Profile Information:**
   - User Avatar
   - Username
   - Name
   - About
   - Followers count
   - Following count
   - Subscribers count
   - Option to share the user profile

2. **Highlighted Publication:**
   - Publication Avatar
   - Publication Name
   - Author's Name
   - About information for the publication

3. **Articles List:**
   - Feature image (if available)
   - Avatar
   - Author Name
   - Reading time
   - Published date
   - Article title
   - Tags associated with the articles

4. **Actions:**
   - Subscribe to the user/author
   - Follow the user/author
   - Edit Profile (for the profile owner)

5. **Views:**
   - **Visitor View:** What any visitor sees when viewing an author's profile.
   - **Owner View:** What the user sees when viewing their own profile.

6. **Theme Support:**
   - Available on Desktop, Tablet, and Mobile.
   - Supports both light and dark themes.

#### Design Reference:
Use the provided screenshots as the design reference for both the visitor view and the owner view.

#### Implementation Steps:

1. **Set up Firestore and Hasura:**
   - Ensure Firestore and Hasura connections are configured.
   - Implement data fetching logic using Redis first, then fallback to Hasura.

2. **Profile Page Components:**
   - Create components for displaying user avatar, username, name, about, followers, following, and subscribers count.
   - Add share profile functionality.

3. **Highlighted Publication:**
   - Create a component to display the highlighted publication details.

4. **Articles List:**
   - Create a component to list articles with all the required details.

5. **Actions:**
   - Implement subscribe and follow functionalities using Firestore endpoints.
   - Add an edit profile button for the owner view.

6. **Views and Themes:**
   - Implement responsive design for desktop, tablet, and mobile.
   - Implement theme switching for light and dark modes.

7. **Testing:**
   - Test all functionalities thoroughly on different devices and themes.
   - Ensure data fetching logic works correctly with both Redis and Hasura.

#### Assets:
- Screenshots provided for design reference:

[Screenshot 1](sandbox:/mnt/data/Screenshot%202024-06-17%20at%2015.24.16.png)
[Screenshot 2](sandbox:/mnt/data/Screenshot%202024-06-17%20at%2015.24.26.png)
![Image](https://github.com/Betarena/boilerplate/assets/37311649/a91683af-cae0-4b5c-b552-5888ac5ad257)

![Image](https://github.com/Betarena/boilerplate/assets/37311649/2bdb0b02-1e62-43a3-9898-a95a6804f0b7)

#### Deliverables:
- Fully functional author profile page.
- Documentation of the implementation and usage.
- Test cases and results.

#### Timeline:
- **Week 1:** Set up data sources and endpoints, create basic profile components.
- **Week 2:** Implement highlighted publication and articles list, add actions.
- **Week 3:** Develop responsive design and theme support, start testing.
- **Week 4:** Complete testing, fix any bugs, and finalize documentation.

Ensure to follow best practices for code quality and maintainability throughout the implementation.

### Feature target platform availability

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop
- [X] 💥 All Devices

### URL

USER:

`{url}/a/user/{username}`

SPORTSTACK

`{url}/a/sportstack/{username}`

#### Data Sources:
- User data: Firestore
- Publications (Sportstack): Hasura (`betarena_prod.authors.authors`)
- Articles: Hasura (`betarena_prod.authors.articles`)
- Use Redis as the primary data store with Hasura as fallback.

#### Endpoints:
- **Subscribe User:** Firestore
- **Follow User:** Firestore

#### Data Logic:
- **Subscribers:** Store subscriber UID.
- **Followers and Following:**
  - Author followers: Store UID.
  - Author following: Store UID.

### ⚡️ Cache

Use the already cached articles on Redis when available.

### 🔎 SEO

Author about
Subscribers Link
Publication name and link
Publication about
on articles:
Publication name and link
Title and link
Tags and links

### 🔎 SEO DETAILS

FOR THE USER PROFILE:

Use the  `betarena_prod   authors   seo_details` table `user`

```
{
  "main_data": {
    "title": "{name} - Betarena",
    "noindex": false,
    "keywords": "{name}, betarena wos",
    "nofollow": false,
    "canonical": "{url}/a/user/{username}",
    "description": "Read writing from {name} on Betarena WOS. {about}"
  },
  "opengraph": {
    "url": "{url}/a/user/{username}",
    "type": "website",
    "title": "{name} - Betarena",
    "images": [
      {
        "alt": "{name} - Betarena",
        "url": "{profile_photo}",
        "width": 88,
        "height": 88
      }
    ],
    "locale": "en",
    "description": "Read writing from {name} on Betarena WOS. {about}"
  },
  "twitter_card": {
    "site": "@betarenasocial",
    "image": "{profile_photo}",
    "title": "{name}, Betarena",
    "image_alt": "{name} - Betarena",
    "description": "Read writing from {name} on Betarena WOS. {about}"
  }
}
```

Variables used:

{name} = Firestore Name
{about} = Firestore About
{profile_photo}  = Firestore Profile Photo

---

SPORTSTACK:

Use the  `betarena_prod   authors   seo_details` table `sportstack`

```
{
  "main_data": {
    "title": "{username} - Betarena",
    "noindex": false,
    "keywords": "{username}, betarena wos",
    "nofollow": false,
    "canonical": "{url}/a/sportstack/{username}",
    "description": "Read writing from {username} on Betarena WOS. {about}"
  },
  "opengraph": {
    "url": "{url}/a/sportstack/{username}",
    "type": "website",
    "title": "{username} - Betarena",
    "images": [
      {
        "alt": "{username} - Betarena",
        "url": "{avatar}",
        "width": 88,
        "height": 88
      }
    ],
    "locale": "en",
    "description": "Read writing from {username} on Betarena WOS. {about}"
  },
  "twitter_card": {
    "site": "@betarenasocial",
    "image": "{avatar}",
    "title": "{username} - Betarena",
    "image_alt": "{username} - Betarena",
    "description": "Read writing from {username} on Betarena WOS. {about}"
  }
}
```

Variables used:

{username} = Hasura
{about} = Hasura
{avatar}  = Hasura

###  TRANSLATIONS

` betarena_prod   translation   author_profile`

### Anything else? Remarks

https://www.figma.com/design/KLZ8I88MggBM3YpHi8jSzj/BTA-Betarena?m=dev&node-id=0-1

### Related projects this feature will involve to achieve

- [X] 🟦 // (frontend) - Scores
- [X] 📦 // (package) - Scores-Lib
- [ ] 🟥 // (worker/backend) - Cache / Sitemap
- [ ] 🟩 // (worker/backend) - Delta Data Manager (C#)
- [ ] 💠 // (package/backend) - Ad-engine
- [x] 🟨 // (worker/backend) - Firebase Functions (backend)

**Comment by migbash** [comment]
**🟧 UPDATE**

- [x] Update `firebase-services` for endpoint accpetance of alternative search for `username` based queries on `firestore`.
↳ **issue** :: _NaN_
↳ **status** :: **🟩 COMPLETED**

- [x] (offspring from previous) Update `scores-lib` for `frontend` to accept valid data for `username` search capbability from `firestore`.
↳ **issue** :: _NaN_
↳ **PR** :: https://github.com/Betarena/scores-lib/pull/352
↳ **PR** :: https://github.com/Betarena/scores-lib/pull/353
↳ **version** :: 3.3.2
↳ **status** :: **🟩 COMPLETED**

----

- [x] Update `scores-lib` for `frontend` to accept valid data for `username` data retireval on target `articles` created by target `user`.
↳ **issue** :: _NaN_
↳ **PR** :: https://github.com/Betarena/scores-lib/pull/354
↳ **PR** :: https://github.com/Betarena/scores-lib/pull/355
↳ **version** :: 3.3.3
↳ **status** :: **🟩 COMPLETED**

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 1. URLs should all be small letters;
- [ ] 2. Wrong width;
- [ ] 3. Wrong grey on followers, following, username;
- [ ] 4. Wrong font settings on the edit my profile;
- [ ] 5. Confirm Avatars size;
- [ ] 6. Sportstacks avatar is square not circle;
- [ ] 7. Wrong space between the top and the articles;
- [ ] 8. Wrong space between the buttons and the sportsack information;
- [ ] 9. The avatar should be in the same position even when the about is missing, the same for the username;
- [ ] 10. Hover is incorrect, should follow the same logic that we have on the other places in the platform;
- [ ] 11. Correct edit my profile link (https://betarena-scores-platform.herokuapp.com/u/settings/en)
- [ ] 12. Placeholders while loading not working;
- [ ] 13. Very slow performance loading the data, specially when navigating from the user to the subscribers list, should be instantly loaded;
- [ ] 14. Subscribers list also missing the placeholders loading;
- [ ] 15. Missing view more articles;


1.

![Image](https://github.com/Betarena/boilerplate/assets/37311649/e387633b-bc25-4d49-b8d5-8c4ff02ca66f)


2, 3, 4, 5, 6, 7, 8, 9

![Image](https://github.com/Betarena/boilerplate/assets/37311649/8349b209-e5b5-4266-abfd-55fc5d139285)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 16. Wrong width;


Still missing several corrections.

16.

![Image](https://github.com/Betarena/boilerplate/assets/37311649/1dba7bc3-7fcc-4461-9bb6-6e99f6a615a8)

**Comment by Izobov** [comment]
@jonsnowpt  8 - it's dynamic, depends on size of "about" information, why do we need a lot of empty space if "about" contains only 1 line of words for example (or no about information at all)?

**Comment by Izobov** [comment]
@jonsnowpt  22 -it's aligned on bottom line if we align it on top by about it will looks different from figma
![image](https://github.com/user-attachments/assets/f49132fc-58a4-4cca-a488-f9bdb5bc681b)
![image](https://github.com/user-attachments/assets/479f5940-14f2-4f38-82be-aa11cab5c1c1)

**Comment by Izobov** [comment]
@jonsnowpt 10 what hovers? what elements?

23 - not clear

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 5. Is still wrong;


5.

![Image](https://github.com/user-attachments/assets/87d980f6-fd62-4513-83c1-164846862cf2)

**Comment by jonsnowpt** [comment]
@Izobov 

For the highlighted user sportstack we should add a new field on the Firestore profile with the highlighted sportstack:

`sportstack_highlight => id `

![Image](https://github.com/user-attachments/assets/7b8f0a67-a6aa-49e6-83c9-8999571431db)

**Comment by Izobov** [comment]
@jonsnowpt  5. depends on about length. In figma "about"  with 3 lines, in reality it could be different. We don't need fixed height for "about" section otherwise there will be a lot of empty space.

![image](https://github.com/user-attachments/assets/2933c5c9-a319-419a-b16e-0be91a9e70b4)

**Comment by Izobov** [comment]
@jonsnowpt how user can set highlited sportstack? And what to do if there's now highlighted sporttack?

**Comment by jonsnowpt** [comment]
@Izobov 

Besides the missing points, we have these issues:

- [ ] 29. Wrong font color and space between the icon and the about ;
- [ ] 30. Missing the people on the Sportstack;
- [ ] 31. Review the colors on the light theme version;
- [ ] 32. When selection following go to following, the same to followers;
- [ ] 33. We need hovers on the users and tabs;


29.

![Image](https://github.com/user-attachments/assets/022935bb-7081-4718-b105-f0d402fd348f)

31.

![Image](https://github.com/user-attachments/assets/93a00ec5-ac2d-4eb8-89b9-bccf2c927b5a)

33.

![Image](https://github.com/user-attachments/assets/cf49df19-3f2a-45a8-97c8-8fdf17044074)

**Comment by Izobov** [comment]
@jonsnowpt 32 what do you mean?

**Comment by jonsnowpt** [comment]
@Izobov 

Missing at this time:

- [ ] 5. Avatars size;
- [ ] 12. Placeholders while loading not working;
- [ ] 14. Subscribers list also missing the placeholders loading;
- [ ]  26. Real-Time followers is not working;
- [ ]  27. Subscribers in real-time is not working;
- [ ] 35. Wrong font size and the avatars have black circle around;
- [ ] 36. Navigation between followers, subscribers works incorrectly and also the back button should be a link to the profile, its not working correctly;


35.

![Image](https://github.com/user-attachments/assets/7ae4c0ce-8d46-41c6-a71a-bce2b7e3b8e5)

36.

https://github.com/user-attachments/assets/ddab4114-284d-4dbf-bdeb-b03c115e4933

**Comment by Izobov** [comment]
@jonsnowpt Is it possible not to change the size when changing the theme? This is probably a designer mistake.
Sportstack tabs on light theme also has 16px

![image](https://github.com/user-attachments/assets/e3a28158-daf7-4772-9c5d-39c8eb3805ac)
![image](https://github.com/user-attachments/assets/0cb39ae9-3ab2-48e9-b704-350dcb1e7b47)

**Comment by jonsnowpt** [comment]
- [ ] 12, Placeholders not working correctly; the articles list does not seem to have the placeholders in place;

12. 

https://github.com/user-attachments/assets/98e866d4-c6db-40ab-aafe-489cacc615ad

**Comment by Izobov** [comment]
42, this is due to our data loading workflow.
Now the client waits for the data to be fully loaded:
1) user
2) first 10 articles + SEO

So, when the page is rendered on the client, we already have 10 articles, no placeholders needed. The reason for loading user information is because from the server we have user = { name, username, ....other_fields, subscribers: [...ids]}
since we need to convert 3 subscribers to profiles, I need to do another fetch on the client side.

At author_profile/draft/1 I proposed a different workflow for data, where we do not wait for 10 articles and there the downloaders are synchronized


Syncing is now easy, just letting you know what's going on here and why it's happening.

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 5. Please check the image;


5. 

![Image](https://github.com/user-attachments/assets/6c8ac189-1b46-4a84-993a-9cde63de73d0)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 43. Transparency 80%


43. 

![Image](https://github.com/user-attachments/assets/3883e1d6-c452-4181-9e1f-f098b9226f73)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 44. Mobile Sportstack share missing image;
- [ ] 45. Missing the space between by and the creator;
- [ ] 46. Add the sportstacks links into the content home, tags and articles (must be added to the SEO);

44. 

![Image](https://github.com/user-attachments/assets/67112896-d225-4f2f-80ea-16829466ecbb)

45. 

![Image](https://github.com/user-attachments/assets/39c4294b-e6f0-4502-ab79-3184f604ffea)

46.

https://betarena-scores-platform.herokuapp.com/a/content

https://betarena-scores-platform.herokuapp.com/a/tag/forecasts

https://betarena-scores-platform.herokuapp.com/a/betarena-soccer/millonarios-vs-atletico-nacional-betting-tip-2024-19169152-1721661377

**Comment by jonsnowpt** [comment]
@Izobov 

Missing:

- [ ] 47. Placeholders on sportstack;
- [ ] 48. Subscribers not being added on the screen;
- [ ] 49. The new subscription should be added from the left to the right, also if our user is subscribed should be kept always in first place;
- [ ] 17. Check this point;
- [ ] 50. Gettins link error, its not user its sportstack (happening on tags and articles);
- [ ] 51. The icon should be included on the link hover;
- [ ] 52. On People should be the name, not the username;


48. 

![Image](https://github.com/user-attachments/assets/8aa932d3-5bd1-47f3-b745-2dfc41647a62)
![Image](https://github.com/user-attachments/assets/03a444d4-9a8e-43e7-b0b5-13dfa385b765)

49. 

![Image](https://github.com/user-attachments/assets/42eadd6e-f97d-4317-a331-65a09c407994)

50 and 51

![Image](https://github.com/user-attachments/assets/d74c2272-3146-40f8-b8ef-ac46673696e7)

52. 

![Image](https://github.com/user-attachments/assets/c4864186-bdc3-4f15-b320-a471ce94425a)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 58. After changing the option on the dropdown the results never appear again only after refresh and navigating through the filter all results stop appearing;
- [ ] 44. Mobile Sportstack share missing image;
- [ ] 17. We will be making the edit my profile larger and hiding the share option, which will not be working for now. 


58. 

https://github.com/user-attachments/assets/71c0983e-ea15-4c47-8906-28af94b42dc4
