### ISSUE TITLE
[FEATURE]: Implement Sportstack Creation Section

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/boilerplate#42]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### Task: Implement Sportstack Creation Section

![Screenshot 2024-09-11 at 15 16 48](https://github.com/user-attachments/assets/efd5dd33-5a95-4040-be5b-4ca6c5445385)

**Objective**  
Create a section in the app where users can name their publication (called "Sportstack"), and either cancel the operation or save the Sportstack. When saving, the system will check name availability, save the Sportstack to the database, and then return the user to the Sportstack list with the newly created publication visible.

**Requirements**
1. **UI Changes (based on attached designs)**:
    - Add two buttons: **Cancel** and **Save**.
    - After clicking **Save**, show a "saving..." message, followed by a "save completed" message.
    - After saving, the user should see a "Continue" button that redirects them back to the Sportstack list with the new publication displayed.

2. **Backend Integration**:
    - Upon saving, insert a new record in the Hasura database with the following structure:
        - **ID**: Auto-incremented integer.
        - **UID**: Unique identifier of the author creating the publication.
        - **DATA**:
          - `username`: Name chosen by the user for the Sportstack.
          - `creation_date`: Timestamp of Sportstack creation.
        - **Status**: Default to "published" upon creation.
        - **Permalink**: URL-friendly version of the chosen Sportstack name.

3. **Real-Time Username Validation**:
    - When the user enters a name for the Sportstack, check in real-time if the name is already taken.
    - Display appropriate success or error messages (e.g., "The name is already in use").

4. **Security Validation**:
    - Ensure the name only contains valid characters for a URL (alphanumeric, hyphens, etc.).
    - Prevent any security risks, such as SQL injection or XSS.

5. **Frontend**:
    - Implement this in **SvelteKit**, ensuring the following flows:
        - **Cancel**: Returns the user to the Sportstack list without saving any data.
        - **Save**: Triggers the real-time username check, performs backend insertions, and handles the UI flow for the saving process.

6. **Localization**:
    - Integrate translations from the `betarena_prod.translation.author_sportstack_creation` table for all user-facing messages.

**Database Reference**  
- **Table**: `betarena_prod.authors`
- **Columns**:
    - `id`: Auto-increment integer.
    - `uid`: Author UID.
    - `data`: JSON structure with author-related data (username, avatar, location, etc.).
    - `subscribers`: List of subscribers.
    - `status`: Status of the publication (active/published).
    - `permalink`: URL-friendly version of the publication name.

---

### Additional Notes:
- Refer to the attached design for button placements and visual flow.
- Handle edge cases such as network failures during the save process.
- For real-time validation, consider debouncing the requests.

FIGMA:

https://www.figma.com/design/HN23FyOG1VhVzKb1CPqets/Sportstack?node-id=0-1&m=dev&t=CFB8Yn5zPlX9ZoKF-1

### ➕ Further context and resources (cummulative)

To address the requirements for creating a **Sportstack** with real-time validation and integrating it with a **Hasura** backend, here are the key steps we can take:

### 1. **Real-Time Name Validation**
To ensure that the Sportstack name is unique, we can implement real-time validation while the user is typing. This involves:

- **Debouncing API calls**: We will only check the name after the user has paused typing for a short period (e.g., 300ms). This prevents excessive requests to the server.
- **Backend check**: The backend will query the database (Hasura) to check if the name already exists in the database.

**Frontend Code Example:**

- Use `on:input` event in **SvelteKit** to trigger the validation.
- Implement a **debounce** mechanism to prevent frequent API calls.

```svelte
<script lang="ts">
  let sportstackName = '';
  let isNameAvailable = null;

  // Debounce function to limit API calls while typing
  let debounceTimer;
  function debounceValidation() {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(validateName, 300); // 300ms debounce
  }

  async function validateName() {
    if (sportstackName.length > 0) {
      const available = await checkNameAvailability(sportstackName);
      isNameAvailable = available;
    }
  }
</script>

<input
  type="text"
  placeholder="Enter sportstack name"
  bind:value={sportstackName}
  on:input={debounceValidation}  <!-- Debounce for input -->
/>

{#if isNameAvailable === false}
  <p class="error">The name is already in use.</p>
{/if}
```

**Backend (Node.js or Express example)**:

```js
import { queryHasura } from './hasura';

// Check if the name is available in the database
export async function post(req, res) {
  const { name } = req.body;
  
  const query = `
    query CheckSportstackName($name: String!) {
      authors(where: {data: {username: {_eq: $name}}}) {
        id
      }
    }
  `;

  const { authors } = await queryHasura(query, { name });

  return res.json({ available: authors.length === 0 });
}
```

### 2. **Form Submission with Validation**

Once the user submits the form, we validate the name again to avoid race conditions (in case multiple users try to create the same Sportstack simultaneously).

- If the name is still available, we proceed to save the new Sportstack.
- We display loading states (e.g., "Saving...") and success or error messages based on the result.

**Frontend Code Example (Saving the Sportstack):**

```svelte
<script lang="ts">
  let isSaving = false;
  let errorMessage = '';

  async function saveSportstack() {
    if (isNameAvailable && sportstackName.length > 0) {
      isSaving = true;
      const result = await createSportstack(sportstackName);
      isSaving = false;
      if (result.success) {
        // Redirect to sportstack list after success
        goto('/sportstacks');
      } else {
        errorMessage = result.message;
      }
    }
  }
</script>

<button on:click={saveSportstack} disabled={isSaving || !isNameAvailable}>
  {#if isSaving}
    Saving...
  {:else}
    Save
  {/if}
</button>

{#if errorMessage}
  <p class="error">{errorMessage}</p>
{/if}
```

### 3. **Backend: Saving to Hasura**
When the user submits a new Sportstack, we insert the relevant data into Hasura’s **authors** table.

- **Input Validation**: Ensure the name is URL-safe (only contains valid characters).
- **Insert Data**: Save the Sportstack to the Hasura database, including the user ID, creation date, status, and permalink.

**Backend (Node.js or Express example):**

```js
import { queryHasura } from './hasura';

export async function post(req, res) {
  const { name, userId, creationDate } = req.body;
  
  // Validate name (only allow valid domain characters)
  const validName = /^[a-zA-Z0-9\-]+$/.test(name);
  if (!validName) {
    return res.json({ success: false, message: 'Invalid name format' });
  }

  // Insert new Sportstack into Hasura
  const mutation = `
    mutation CreateSportstack($name: String!, $userId: String!, $creationDate: timestamptz!) {
      insert_authors_one(object: {
        uid: $userId,
        data: {
          username: $name,
          creation_date: $creationDate
        },
        status: "published",
        permalink: $name
      }) {
        id
      }
    }
  `;

  try {
    const result = await queryHasura(mutation, { name, userId, creationDate });
    return res.json({ success: true });
  } catch (error) {
    return res.json({ success: false, message: 'Failed to create sportstack' });
  }
}
```

### 4. **Security Considerations**
- **Input validation**: Ensure that only safe characters are allowed for Sportstack names (e.g., alphanumeric and hyphens). This prevents security vulnerabilities like SQL injection or XSS.
- **Hasura permissions**: Ensure that only authenticated users can create new Sportstacks by configuring permissions in Hasura.

### 5. **UI Feedback**
- **Loading States**: Provide a visual cue when the system is processing the save request (e.g., "Saving...").
- **Success/Error Messages**: After saving, show whether the operation succeeded or failed.
- **Redirection**: Once the Sportstack is successfully created, redirect the user back to the Sportstack list, where they can see the new publication.

### Summary of the Flow:

1. **Real-time validation** of the Sportstack name as the user types.
2. If the name is available, the user can **save** the Sportstack.
3. Upon saving, the **backend inserts** the new Sportstack into Hasura.
4. The user is redirected back to the **Sportstack list** to see their newly created publication.

This setup provides a smooth user experience with real-time feedback, strong input validation, and secure backend handling.

**Comment by jonsnowpt** [comment]
@Izobov 

REVIEW:

- [ ] 1. Change the order, Author after settings;
- [ ] 2. Cancel and Save must be always present;
- [ ] 3. Incorrect CSS for the "Cancel" option;

1. ![Image](https://github.com/user-attachments/assets/a1b50f9e-8a97-4dfd-a3d6-ccc48121b3e9)

2. ![Image](https://github.com/user-attachments/assets/39c75c40-dcc6-4b96-8efa-d55aa7fe92c3)

3. ![Image](https://github.com/user-attachments/assets/7f050108-8265-49be-b0b6-41ca81dfb87b)

**Comment by Izobov** [comment]
@jonsnowpt 2 it's because of show notification button, if I hide it everything will be okay

**Comment by jonsnowpt** [comment]
@Izobov, you can remove it; we will not need it anymore.

**Comment by Izobov** [comment]
3 need to be discussed with designer. This button from BTA design 2.0 and button named same as one of button from 1.0 
So probably we are going to change css for all the buttons instanced from this type

**Comment by Izobov** [comment]
> @Izobov, you can remove it; we will not need it anymore.

Okay

**Comment by Izobov** [comment]
@jonsnowpt 6 it's depends on your phone screen size. If you will have exact same size as on figma maket 375px, You will have exactly same width ![Image](https://github.com/user-attachments/assets/ee05e752-1ed6-4e37-8c85-ec671487fb99)
![Image](https://github.com/user-attachments/assets/2d5eca00-5db6-4a70-a749-25938e11071a)
 ![Image](https://github.com/user-attachments/assets/73cf0cd6-32bb-441f-b441-95d118f7f42b)

**Comment by Izobov** [comment]
@jonsnowpt as for cancel css button. I reused button that we have in other parts of app to keep it in one style

![Image](https://github.com/user-attachments/assets/b8444394-5e41-4788-8a0e-bb131320ae3f)
![Image](https://github.com/user-attachments/assets/fa155343-a11b-455e-bea5-714754d54b66)
![Image](https://github.com/user-attachments/assets/3822a38d-1bbf-45b3-8084-6225c8195708)
![Image](https://github.com/user-attachments/assets/41c19658-a2b0-49b4-866a-92168f340f1d)
